server:
  port: 8182
spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group  #自定义事务组名称需要与seata-server中的对应,对应本地seata/conf/file.conf的service { vgroup_mapping.fsp_tx_group = "default" #修改自定义事务组名称
    nacos:
      discovery:
        server-addr: localhost:8848  #注册中心，对应的是seata/conf/registry.conf里面的nacos配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/seata-account
    username: root
logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml
