server:
  port: 8904
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置中心git地址
          uri: https://github.com/1241055166/spring-cloud-config.git
          username: 1241055166@qq.com          #github用户名
          password: zaq123456789zaq.           #github密码
          clone-on-start: true # 开启启动时直接从git获取配置
  rabbitmq: #rabbitmq相关配置
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'