server:   #config-server 集群的配置
  port: 8903
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置中心git地址
          uri: https://github.com/1241055166/spring-cloud-config.git
          username: 1241055166@qq.com          #github用户名
          password: zaq123456789zaq.           #github密码
          clone-on-start: true # 开启启动时直接从git获取配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
